/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidateDto } from './candidateDto';


export interface VoteResponse { 
    sectionId?: number;
    sectionName?: string;
    ballotOpen?: boolean;
    totalVotes?: number;
    blanks?: number;
    nulls?: number;
    countingInProgress?: boolean;
    leadPartyList?: string;
    sectionClosed?: number;
    mayors?: Array<CandidateDto>;
    councilors?: Array<CandidateDto>;
}

